general {
  # trava a sesão
  lock_cmd            = pidof hyprlock || hyprlock
  # bloqueia asnte de suspender
  before_sleep_cmd    = loginctl lock-session
  # volta a ligar o monitor depois de acordar
  after_sleep_cmd     = hyprctl dispatch dpms on
  ignore_dbus_inhibit = false
}


# bloqueia a tela depois de 4 minutos de inatividade
listener {
  timeout     = 240
  on-timeout  = pidof hyprlock || hyprlock
}

# desliga o monitor depois de 5 minutos de inatividade
listener {
  timeout     = 340
  on-timeout  = hyprctl dispatch dpms off
  # liga novamente ao mover o mouse
  on-resume   = hyprctl dispatch dpms on
}

# suspende o sistema depois de 10 minutos de inatividade
listener {
  timeout     = 600
  on-timeout  = systemctl suspend
}